### ISSUE TITLE
Extracting the reverb filter (.wav) from YP-Q2's original firmware

### ISSUE THREAD

**Issue by gogo9th** [LemonBoy/Q2-Tools#1]
Hi,

For recent 2 years, I've been trying to extract the reverb filter (.wav) from YP-Q2's original firmware, but was not successful, and I finally found your github repository. I wonder if your tool is also for extracting the original firmware from the device. If so, could you please give me a little more clue on how to use your software package for this task? 

Another question is, if we can decompile the firmware update file, will this contain the entirety of Q2's runnable firmware? If so, how can we decompile it? I tried with Hex-ray, but for some reason this was not successful... Thanks very much.

**Comment by LemonBoy** [comment]
> For recent 2 years, I've been trying to extract the reverb filter (.wav) from YP-Q2's original firmware

There's no wav file in the unpacked firmware, the only audio file I see is a test tone named `05_1KHz,0dB.mp3`.
Are you sure the reverb effect is not done in the player software itself (or in some DSP rom)?

There's an `unpack.sh` script that explains a bit how to compile/run the decrypting utility and turn the `Q2Update.dat` into a plain `tar.gz` archive. You then have to extract the rootfs (a `squashfs` image) and the appfs (a `cramfs` image), you can probably use 7zip to open all of them if you are on Windows.

> Another question is, if we can decompile the firmware update file, will this contain the entirety of Q2's runnable firmware? If so, how can we decompile it? I tried with Hex-ray, but for some reason this was not successful... 

Yes, the player software is called `AppMain` and I've reverse-engineered a great part of it a [few weeks ago](https://github.com/LemonBoy/elf2aab) to find out how to build my own `.aab` games. 
Forget IDA, use [ghidra](https://ghidra-sre.org/) and a lot of patience.

**Comment by gogo9th** [comment]
Thanks very much for your tip. I am really amazed that you made this!

I could manage to extract appfs and found AppMain. However, I cannot decompile AppMain by using your elf2aab.py due to the following assertion error (8 segments instead of 1):

```
:q2update_unpacked/appfs$ python3 ~/Desktop/elf2aab-master/elf2aab.py bin/AppMain
Processing file: bin/AppMain
8
Traceback (most recent call last):
  File "/home/skyer/Desktop/elf2aab-master/elf2aab.py", line 123, in <module>
    process_file(filename)
  File "/home/skyer/Desktop/elf2aab-master/elf2aab.py", line 15, in process_file
    assert(elffile.num_segments() == 1)
AssertionError
```

Basically, my goal is to reverse-engineer the routine which applies the Cathedral effect (or reverb effect) to the music file and implement this in Python or another language on my own. Do you think this routine is inside AppMain? I would really appreciate your kind help once again...

**Comment by LemonBoy** [comment]
> However, I cannot decompile AppMain by using your elf2aab.py due to the following assertion error (8 segments instead of 1):

elf2aab is a tool to build your own games (such as the chicken one), I only mentioned it because all the information I needed to build it were obtained by decompiling `AppMain` using ghidra.

> Basically, my goal is to reverse-engineer the routine which applies the Cathedral effect (or reverb effect) to the music file and implement this in Python or another language on my own. Do you think this routine is inside AppMain? 

You're quite lucky, `libmediaserv.so` does all the audio filtering and it still has all its symbols!

**Comment by gogo9th** [comment]
Got it, I managed to decompile functions in .so files by using Ghidra and this is really cool. I think I can understand and implement the reverb logic. Thanks again! 

Could I ask just one more small question..? Using Ghidra, I can decompile each function in the navigation window one by one by double-clicking each. However, I wonder if Ghidra has the feature to decompile a chosen entire .so or .exe file (I suppose not?)

**Comment by LemonBoy** [comment]
> However, I wonder if Ghidra has the feature to decompile a chosen entire .so or .exe file (I suppose not?)

No idea, if you dump everything into a text file you lose every form of interactivity (eg. local variable renaming & typing) that are immensely helpful.

**Comment by gogo9th** [comment]
Okay, that's true. Thanks again and it was extremely lucky for me to bump into your repository today :)

**Comment by gogo9th** [comment]
Hi, I has some request regarding this firmware and I'd like to talk about it by email... (realmemory2002@gmail.com). If you could, please send me a message, thanks.

**Comment by gogo9th** [comment]
Hi, 

I am currently reverse-engineering and implementing the Reverb algorithm based on Ghidra. But I am facing an issue and I wonder if you could give me little clues...

In the libMediaSrv.so file's HP_AddReverb function, there is the following code:

`      if (iVar2 + 0x8000 < 0 != SCARRY4(iVar2,0x8000)) {`

And there is no function definition for `SCARRY4`. So I suppose this is a macro. But I could not figure out how to find macro definitions in Ghidra.. The Symbol Tree tab has only Imports, Exports, Functions, Labels, Classes, and Namespaces.

Also, is there a way to find global variable definitions in Ghidra?

**Comment by LemonBoy** [comment]
`SCARRY` is part of Ghidra IL, you can find more info [here](https://ghidra.re/courses/languages/html/reference.html).

> Also, is there a way to find global variable definitions in Ghidra?

All the symbols starting with `DAT_` should be globals, can't remember how (nor if there's a way) to list them all.

**Comment by gogo9th** [comment]
I see, so it's checking if the carry bit is on or off... Thanks for the tip!

**Comment by gogo9th** [comment]
Finally done

https://github.com/gogo9th/yp-q2-cathedral

Online version

http://46.101.121.219:3000
